language: python
dist: xenial
os:
  - linux

python:
  - 3.9
  - 3.10-dev
  - nightly

cache:
  pip: false

before_install:
  - python --version
  - uname -a

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

notifications:
  email:
    recipients:
      - stanisov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

script:
  - python setup.py test
after_script:
  - coverage report
after_success:
    coveralls